module.exports = {
  content: [
    "./pages/**/*.{js,jsx,ts,tsx,md,mdx}",
    "./components/**/*.{js,jsx,ts,tsx,md,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "sidebar-bg": "#29348E",
        "primary-brand": "#ED4B9E",
        "secondary-brand": "#4B4DED",
        "tertiary-brand": "#F3D9DA",
        dark: "#0E0E2C",
        success: "#31D0AA",
        text: "#4A4A68",
        "subtle-text": "#8C8CA1",
        "hover-color": "hsla(191, 100%, 63%, 0.5)",
        "hover-color2": "#ECF8FF",
        // "background": "#F6F7F9",
        background: "#F7F6FB",
        // "hover-color": "hsla(191, 100%, 63%, 0.23)",
        "menu-hover": "#618CFB",
        "blue-quiz-answer": "#3B5ADB",
        "fiolet-quiz-answer": "#BF44DE",
        "red-quiz-answer": "#DA3434",
        "green-quiz-answer": "#45B829",
        "border-filter": "#E7E8E9",
        "my-account-menu-hover": "#DFECFF",
        "edycja-quiz": "#83BCFF",
        "delete-quiz": "#FF7171",
        "platnosci-line-border": "#CBCBCB",
        "platnosci-faktura": "#5E83E0",
        "platnosci-zaplac-blikiem": "#33B970",
        "settings-success": "#33B970",
        "ustawienia-menu": "#ECF8FF",
        "wreid-block": "#D0D0D0",
        "another-wreid": "#AAAAAA",
        small: "#BCBCBC",
        gray: "#A5A5A5",
        "waiting-yellow": "#DDC755",
        "error-red": "#DF5D5D",
        "blocky-purple": "#F3F0FF",
        "platnosci-text": "#939393",
        positive: "#00CC52",
        "positive-bg": "#F3FFF6",
        negative: "#CC0000",
        "negative-button": "#FF0000",
        "negative-bg": "#FEF4F4",
        "input-bg": "#F9F9F9",
        "standard-user":"#D4F8CB",
        "premium-user": "#FFF6D7",
      },
    },
  },
  plugins: [],
};
